variable "env" {}
variable "name_tag" {}
variable "my_vpc_id" {}  
variable "public_subnet1_id" {}
variable "public_subnet2_id" {}
variable "private_subnet1_nat_id" {}
variable "private_subnet2_nat_id" {}  
variable "private_subnet3_id" {}
variable "private_subnet4_id" {}
variable "private_subnet5_id" {}
variable "private_subnet6_id" {}
